export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"
export const IS_USER_LOGGED = "IS_USER_LOGGED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS"
export const LOG_OUT_ERROR = "LOG_OUT_ERROR"
export const GET_NEWS = "GET_NEWS"