export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOADING_START = "LOADING_START"
export const LOADING_FINISH = "LOADING_FINISH"
export const GET_NEWS = "GET_NEWS"
export const SET_LATEST_NEWS_ERROR = "SET_LATEST_NEWS_ERROR"
export const SET_LATEST_NEWS = "SET_LATEST_NEWS"